version: '3'

services:
  needoff:
    build: .
    ports:
      - "3344:3344"
    restart: always
    environment:
      APPLICATION_SETTINGS: '../config/docker.py'
    volumes:
      - .:/app
      - ./db:/db
